name: Alertas Automáticas

on:
  schedule:
    - cron: '0 13 * * *'

  workflow_dispatch:

jobs:
  ejecutar-alertas:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar alertas
        run: |
          python alertas.py